document.write("<nav id=\"HeaderNavigation\">");
document.write("<div id=\"Container_HeaderNavigation\">");
document.write("<a href=\"http:\//www.ynou.cn/\">");
document.write("<img src=\"Attachments/_Base/wfu_icon.png\" style=\"height:84px; float: left; margin:7px 20px;\">");
document.write("</a>");
document.write("<div id=\"Navigation\">");
document.write("<ul>");
document.write("<li><a href=\"Default.html\">课程首页</a></li>");
document.write("<li><a href=\"Syllabus.html\">教学计划</a></li>");
document.write("<li><a href=\"Practice.html\">课程实训</a></li>");
document.write("<li><a href=\"LectureVideos.html\">教学视频</a></li>");
document.write("</ul>");
document.write("</div>");
document.write("</div>");
document.write("</nav>");